name: build
on:
  push:
  pull_request:
    branches: [ main, develop ]
env:
  DOTNET_VERSION: '6.0.x'
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Install dependencies
        run: dotnet restore
        working-directory: src
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: src